# flake8: noqa
import logging
from datetime import date
from app.main.config import CONFIG
from app.main.service import city_service, user_service


def _create_user(username: str, password: str):
    user = user_service.get_by_username(username=username)
    if not user:
        user = user_service.add(username=username, password=password)
    return user


def _create_simle_name_entity(service, name_ua: str, name_en: str):
    entity = service.get_by_name(name=name_ua)
    if not entity:
        entity = service.add(name_ua=name_ua, name_en=name_en)
    return entity



def create_mandatory_info():
    logging.info("Creating admins")
    evader = _create_user(username="superadmin", password="pas from env environment")


def create_standart_info():
    logging.info("Creating standart infor for store items")
    kyiv = _create_simle_name_entity(service=city_service, name_ua="Київ", name_en="Kyiv")
    kharkiv = _create_simle_name_entity(service=city_service, name_ua="Харків", name_en="Kharkiv")
    odesa = _create_simle_name_entity(service=city_service, name_ua="Одеса", name_en="Odesa")
    dnipro = _create_simle_name_entity(service=city_service, name_ua="Дніпро", name_en="Dnipro")
    lviv = _create_simle_name_entity(service=city_service, name_ua="Львів", name_en="Lviv")
    mykolaiv = _create_simle_name_entity(service=city_service, name_ua="Миколаїв", name_en="Mykolaiv")
    sevastopol = _create_simle_name_entity(service=city_service, name_ua="Севасто́поль", name_en="Sevastopol")
    kremenchuk = _create_simle_name_entity(service=city_service, name_ua="Кременчук", name_en="Kremenchuk")
    pokrovsk = _create_simle_name_entity(service=city_service, name_ua="Покровськ", name_en="Pokrovsk")
    ivano_frankivsk = _create_simle_name_entity(service=city_service, name_ua="Івано-Франківськ", name_en="Ivano-Frankivsk")
    sumy = _create_simle_name_entity(service=city_service, name_ua="Суми", name_en="Sumy")
    cherkasy = _create_simle_name_entity(service=city_service, name_ua="Черкаси", name_en="Cherkasy")

    donetsk = _create_simle_name_entity(service=city_service, name_ua="Донецьк", name_en="Donetsk")
    zaporizhzhia = _create_simle_name_entity(service=city_service, name_ua="Запоріжжя", name_en="Zaporizhzhia")
    kryvyi_rih = _create_simle_name_entity(service=city_service, name_ua="Кривий Ріг", name_en="Kryvyi Rih")
    mariupol = _create_simle_name_entity(service=city_service, name_ua="Маріуполь", name_en="Mariupol")
    luhansk = _create_simle_name_entity(service=city_service, name_ua="Луганськ", name_en="Luhansk")
    vinnytsia = _create_simle_name_entity(service=city_service, name_ua="Вінниця", name_en="Vinnytsia")
    makiivka = _create_simle_name_entity(service=city_service, name_ua="Макіївка", name_en="Makiivka")
    simferopol = _create_simle_name_entity(service=city_service, name_ua="Сімферополь", name_en="Simferopol")
    chernihiv = _create_simle_name_entity(service=city_service, name_ua="Чернігів", name_en="Chernihiv")
    kherson = _create_simle_name_entity(service=city_service, name_ua="Херсон", name_en="Kherson")
    poltava = _create_simle_name_entity(service=city_service, name_ua="Полтава", name_en="Poltava")
    khmelnytskyi = _create_simle_name_entity(service=city_service, name_ua="Хмельницький", name_en="Khmelnytskyi")
    chernivtsi = _create_simle_name_entity(service=city_service, name_ua="Чернівці", name_en="Chernivtsi")
    zhytomyr = _create_simle_name_entity(service=city_service, name_ua="Житомир", name_en="Zhytomyr")
    rivne = _create_simle_name_entity(service=city_service, name_ua="Рівне", name_en="Rivne")
    horlivka = _create_simle_name_entity(service=city_service, name_ua="Горлівка", name_en="Horlivka")
    kamianske = _create_simle_name_entity(service=city_service, name_ua="Кам'янське", name_en="Kamianske")
    ternopil = _create_simle_name_entity(service=city_service, name_ua="Тернопіль", name_en="Ternopil")
    kropyvnytskyi = _create_simle_name_entity(service=city_service, name_ua="Кропивницький", name_en="Kropyvnytskyi")
    lutsk = _create_simle_name_entity(service=city_service, name_ua="Луцьк", name_en="Lutsk")
    bila_tserkva = _create_simle_name_entity(service=city_service, name_ua="Біла Церква", name_en="Bila Tserkva")
    kerch = _create_simle_name_entity(service=city_service, name_ua="Керч", name_en="Kerch")
    melitopol = _create_simle_name_entity(service=city_service, name_ua="Мелітополь", name_en="Melitopol")
    kramatorsk = _create_simle_name_entity(service=city_service, name_ua="Краматорськ", name_en="Kramatorsk")
    uzhhorod = _create_simle_name_entity(service=city_service, name_ua="Ужгород", name_en="Uzhhorod")
    brovary = _create_simle_name_entity(service=city_service, name_ua="Бровари", name_en="Brovary")
    yevpatoria = _create_simle_name_entity(service=city_service, name_ua="Євпаторія", name_en="Yevpatoria")
    berdiansk = _create_simle_name_entity(service=city_service, name_ua="Бердянськ", name_en="Berdiansk")
    nikopol = _create_simle_name_entity(service=city_service, name_ua="Нікополь", name_en="Nikopol")
    sloviansk = _create_simle_name_entity(service=city_service, name_ua="Слов'янськ", name_en="Sloviansk")
    alchevsk = _create_simle_name_entity(service=city_service, name_ua="Алчевськ", name_en="Alchevsk")
    pavlohrad = _create_simle_name_entity(service=city_service, name_ua="Павлоград", name_en="Pavlohrad")
    sievierodonetsk = _create_simle_name_entity(service=city_service, name_ua="Сєвєродонецьк", name_en="Sievierodonetsk")
    kamianets_podilskyi = _create_simle_name_entity(service=city_service, name_ua="Кам'янець-Подільський", name_en="Kamianets-Podilskyi")
    lysychansk = _create_simle_name_entity(service=city_service, name_ua="Лисичанськ", name_en="Lysychansk")
    mukachevo = _create_simle_name_entity(service=city_service, name_ua="Мукачево", name_en="Mukachevo")
    konotop = _create_simle_name_entity(service=city_service, name_ua="Конотоп", name_en="Konotop")
    uman = _create_simle_name_entity(service=city_service, name_ua="Умань", name_en="Uman")
    krasnyi_luch = _create_simle_name_entity(service=city_service, name_ua="Хрустальний (Khrustalnyi)", name_en="Krasnyi Luch")
    yalta = _create_simle_name_entity(service=city_service, name_ua="Ялта", name_en="Yalta")
    oleksandriia = _create_simle_name_entity(service=city_service, name_ua="Олександрія", name_en="Oleksandriia")
    yenakiieve = _create_simle_name_entity(service=city_service, name_ua="Єнакієве", name_en="Yenakiieve")
    drohobych = _create_simle_name_entity(service=city_service, name_ua="Дрогобич", name_en="Drohobych")
    berdychiv = _create_simle_name_entity(service=city_service, name_ua="Бердичів", name_en="Berdychiv")
    stakhanov = _create_simle_name_entity(service=city_service, name_ua="Кадіївка (Kadiivka)", name_en="Stakhanov")
    shostka = _create_simle_name_entity(service=city_service, name_ua="Шостка", name_en="Shostka")
    bakhmut = _create_simle_name_entity(service=city_service, name_ua="Бахмут", name_en="Bakhmut")
    izmail = _create_simle_name_entity(service=city_service, name_ua="Ізмаїл", name_en="Izmail")
    novomoskovsk = _create_simle_name_entity(service=city_service, name_ua="Новомосковськ", name_en="Novomoskovsk")
    kostiantynivka = _create_simle_name_entity(service=city_service, name_ua="Костянтинівка", name_en="Kostiantynivka")
    kovel = _create_simle_name_entity(service=city_service, name_ua="Ковель", name_en="Kovel")
    feodosia = _create_simle_name_entity(service=city_service, name_ua="Феодосія", name_en="Feodosia")
    nizhyn = _create_simle_name_entity(service=city_service, name_ua="Ніжин", name_en="Nizhyn")
    smila = _create_simle_name_entity(service=city_service, name_ua="Сміла", name_en="Smila")
    kalush = _create_simle_name_entity(service=city_service, name_ua="Калуш", name_en="Kalush")
    chervonohrad = _create_simle_name_entity(service=city_service, name_ua="Червоноград", name_en="Chervonohrad")
    boryspil = _create_simle_name_entity(service=city_service, name_ua="Бориспіль", name_en="Boryspil")
    pervomaisk = _create_simle_name_entity(service=city_service, name_ua="Первомайськ", name_en="Pervomaisk")
    sverdlovsk = _create_simle_name_entity(service=city_service, name_ua="Довжанськ (Dovzhansk)", name_en="Sverdlovsk")
    irpin = _create_simle_name_entity(service=city_service, name_ua="Ірпінь", name_en="Irpin")
    korosten = _create_simle_name_entity(service=city_service, name_ua="Коростень", name_en="Korosten")
    kolomyia = _create_simle_name_entity(service=city_service, name_ua="Коломия", name_en="Kolomyia")
    stryi = _create_simle_name_entity(service=city_service, name_ua="Стрий", name_en="Stryi")
    chornomorsk = _create_simle_name_entity(service=city_service, name_ua="Чорноморськ", name_en="Chornomorsk")
    khartsyzk = _create_simle_name_entity(service=city_service, name_ua="Харцизьк", name_en="Khartsyzk")
    rubizhne = _create_simle_name_entity(service=city_service, name_ua="Рубіжне", name_en="Rubizhne")
    zviahel = _create_simle_name_entity(service=city_service, name_ua="Звягель", name_en="Zviahel")
    druzhkivka = _create_simle_name_entity(service=city_service, name_ua="Дружківка", name_en="Druzhkivka")
    lozova = _create_simle_name_entity(service=city_service, name_ua="Лозова", name_en="Lozova")
    chystiakove = _create_simle_name_entity(service=city_service, name_ua="Чистякове", name_en="Chystiakove")
    enerhodar = _create_simle_name_entity(service=city_service, name_ua="Енергодар", name_en="Enerhodar")
    pryluky = _create_simle_name_entity(service=city_service, name_ua="Прилуки", name_en="Pryluky")
    antratsyt = _create_simle_name_entity(service=city_service, name_ua="Антрацит", name_en="Antratsyt")
    novovolynsk = _create_simle_name_entity(service=city_service, name_ua="Нововолинськ", name_en="Novovolynsk")
    horishni_plavni = _create_simle_name_entity(service=city_service, name_ua="Горішні Плавні", name_en="Horishni Plavni")
    shakhtarsk = _create_simle_name_entity(service=city_service, name_ua="Шахтарськ", name_en="Shakhtarsk")
    bilhorod_dnistrovskyi = _create_simle_name_entity(service=city_service, name_ua="Білгород-Дністровський", name_en="Bilhorod-Dnistrovskyi")
    okhtyrka = _create_simle_name_entity(service=city_service, name_ua="Охтирка", name_en="Okhtyrka")
    myrnohrad = _create_simle_name_entity(service=city_service, name_ua="Мирноград", name_en="Myrnohrad")
    snizhne = _create_simle_name_entity(service=city_service, name_ua="Сніжне", name_en="Snizhne")
    izium = _create_simle_name_entity(service=city_service, name_ua="Ізюм", name_en="Izium")
    marhanets = _create_simle_name_entity(service=city_service, name_ua="Марганець", name_en="Marhanets")
    rovenky = _create_simle_name_entity(service=city_service, name_ua="Ровеньки", name_en="Rovenky")
    nova_kakhovka = _create_simle_name_entity(service=city_service, name_ua="Нова Каховка", name_en="Nova Kakhovka")
    brianka = _create_simle_name_entity(service=city_service, name_ua="Брянка", name_en="Brianka")
    fastiv = _create_simle_name_entity(service=city_service, name_ua="Фастів", name_en="Fastiv")
    lubny = _create_simle_name_entity(service=city_service, name_ua="Лубни", name_en="Lubny")
    svitlovodsk = _create_simle_name_entity(service=city_service, name_ua="Світловодськ", name_en="Svitlovodsk")
    zhovti_vody = _create_simle_name_entity(service=city_service, name_ua="Жовті Води", name_en="Zhovti Vody")
    krasnodon = _create_simle_name_entity(service=city_service, name_ua="Сорокине (Sorokyne)", name_en="Krasnodon")
    vyshneve = _create_simle_name_entity(service=city_service, name_ua="Вишневе", name_en="Vyshneve")
    varash = _create_simle_name_entity(service=city_service, name_ua="Вараш", name_en="Varash")
    shepetivka = _create_simle_name_entity(service=city_service, name_ua="Шепетівка", name_en="Shepetivka")
    podilsk = _create_simle_name_entity(service=city_service, name_ua="Подільськ", name_en="Podilsk")
    yuzhnoukrainsk = _create_simle_name_entity(service=city_service, name_ua="Южноукраїнськ", name_en="Yuzhnoukrainsk")
    myrhorod = _create_simle_name_entity(service=city_service, name_ua="Миргород", name_en="Myrhorod")
    romny = _create_simle_name_entity(service=city_service, name_ua="Ромни", name_en="Romny")
    pokrov = _create_simle_name_entity(service=city_service, name_ua="Покров", name_en="Pokrov")
    volodymyr = _create_simle_name_entity(service=city_service, name_ua="Володимир", name_en="Volodymyr")
    dzhankoi = _create_simle_name_entity(service=city_service, name_ua="Джанкой", name_en="Dzhankoi")
    vasylkiv = _create_simle_name_entity(service=city_service, name_ua="Васильків", name_en="Vasylkiv")
    dubno = _create_simle_name_entity(service=city_service, name_ua="Дубно", name_en="Dubno")
    bucha = _create_simle_name_entity(service=city_service, name_ua="Буча", name_en="Bucha")
    netishyn = _create_simle_name_entity(service=city_service, name_ua="Нетішин", name_en="Netishyn")
    pervomaisk = _create_simle_name_entity(service=city_service, name_ua="Первомайськ", name_en="Pervomaisk")
    kakhovka = _create_simle_name_entity(service=city_service, name_ua="Каховка", name_en="Kakhovka")
    boyarka = _create_simle_name_entity(service=city_service, name_ua="Боярка", name_en="Boyarka")
    slavuta = _create_simle_name_entity(service=city_service, name_ua="Славута", name_en="Slavuta")
    sambir = _create_simle_name_entity(service=city_service, name_ua="Самбір", name_en="Sambir")
    yasynuvata = _create_simle_name_entity(service=city_service, name_ua="Ясинувата", name_en="Yasynuvata")
    starokostiantyniv = _create_simle_name_entity(service=city_service, name_ua="Староко­стянтинів", name_en="Starokostiantyniv")
    zhmerynka = _create_simle_name_entity(service=city_service, name_ua="Жмеринка", name_en="Zhmerynka")
    voznesensk = _create_simle_name_entity(service=city_service, name_ua="Вознесенськ", name_en="Voznesensk")
    obukhiv = _create_simle_name_entity(service=city_service, name_ua="Обухів", name_en="Obukhiv")
    boryslav = _create_simle_name_entity(service=city_service, name_ua="Борислав", name_en="Boryslav")
    yuzhne = _create_simle_name_entity(service=city_service, name_ua="Южне", name_en="Yuzhne")
    vyshhorod = _create_simle_name_entity(service=city_service, name_ua="Вишгород", name_en="Vyshhorod")
    hlukhiv = _create_simle_name_entity(service=city_service, name_ua="Глухів", name_en="Hlukhiv")
    avdiivka = _create_simle_name_entity(service=city_service, name_ua="Авдіївка", name_en="Avdiivka")
    chuhuiv = _create_simle_name_entity(service=city_service, name_ua="Чугуїв", name_en="Chuhuiv")
    toretsk = _create_simle_name_entity(service=city_service, name_ua="Торецьк", name_en="Toretsk")
    novoiavorivsk = _create_simle_name_entity(service=city_service, name_ua="Новояворівськ", name_en="Novoiavorivsk")
    kostopil = _create_simle_name_entity(service=city_service, name_ua="Костопіль", name_en="Kostopil")
    alushta = _create_simle_name_entity(service=city_service, name_ua="Алушта", name_en="Alushta")
    mohyliv_podilskyi = _create_simle_name_entity(service=city_service, name_ua="Могилів-Подільський", name_en="Mohyliv-Podilskyi")
    tokmak = _create_simle_name_entity(service=city_service, name_ua="Токмак", name_en="Tokmak")
    synelnykove = _create_simle_name_entity(service=city_service, name_ua="Синельникове", name_en="Synelnykove")
    pervomaiskyi = _create_simle_name_entity(service=city_service, name_ua="Первомайський", name_en="Pervomaiskyi")
    sarny = _create_simle_name_entity(service=city_service, name_ua="Сарни", name_en="Sarny")
    dobropillia = _create_simle_name_entity(service=city_service, name_ua="Добропілля", name_en="Dobropillia")
    truskavets = _create_simle_name_entity(service=city_service, name_ua="Трускавець", name_en="Truskavets")
    chortkiv = _create_simle_name_entity(service=city_service, name_ua="Чортків", name_en="Chortkiv")
    khust = _create_simle_name_entity(service=city_service, name_ua="Хуст", name_en="Khust")
    novyi_rozdil = _create_simle_name_entity(service=city_service, name_ua="Новий розділ", name_en="Novyi Rozdil")
    pershotravensk = _create_simle_name_entity(service=city_service, name_ua="Першотравенськ", name_en="Pershotravensk")
    zolotonosha = _create_simle_name_entity(service=city_service, name_ua="Золотоноша", name_en="Zolotonosha")
    kirovske = _create_simle_name_entity(service=city_service, name_ua="Хрестівка (Khrestivka)", name_en="Kirovske")
    ternivka = _create_simle_name_entity(service=city_service, name_ua="Тернівка", name_en="Ternivka")
    kupiansk = _create_simle_name_entity(service=city_service, name_ua="Куп'янськ", name_en="Kupiansk")
    khmilnyk = _create_simle_name_entity(service=city_service, name_ua="Хмільник", name_en="Khmilnyk")
    balakliia = _create_simle_name_entity(service=city_service, name_ua="Балаклія", name_en="Balakliia")
    kirovsk = _create_simle_name_entity(service=city_service, name_ua="Голубівка (Holubivka)", name_en="Kirovsk")
    pereiaslav = _create_simle_name_entity(service=city_service, name_ua="Переяслав", name_en="Pereiaslav")
    bakhchysarai = _create_simle_name_entity(service=city_service, name_ua="Бахчисарай", name_en="Bakhchysarai")
    haisyn = _create_simle_name_entity(service=city_service, name_ua="Гайсин", name_en="Haisyn")
    malyn = _create_simle_name_entity(service=city_service, name_ua="Малин", name_en="Malyn")
    vynohradiv = _create_simle_name_entity(service=city_service, name_ua="Виноградів", name_en="Vynohradiv")
    perevalsk = _create_simle_name_entity(service=city_service, name_ua="Перевальськ", name_en="Perevalsk")
    slavutych = _create_simle_name_entity(service=city_service, name_ua="Славутич", name_en="Slavutych")
    krasnoperekopsk = _create_simle_name_entity(service=city_service, name_ua="Краснопере­копськ", name_en="Krasnoperekopsk")
    zdolbuniv = _create_simle_name_entity(service=city_service, name_ua="Здолбунів", name_en="Zdolbuniv")
    korostyshiv = _create_simle_name_entity(service=city_service, name_ua="Коростишів", name_en="Korostyshiv")
    oleshky = _create_simle_name_entity(service=city_service, name_ua="Олешки", name_en="Oleshky")
    debaltseve = _create_simle_name_entity(service=city_service, name_ua="Дебальцеве", name_en="Debaltseve")
    saky = _create_simle_name_entity(service=city_service, name_ua="Саки", name_en="Saky")
    lebedyn = _create_simle_name_entity(service=city_service, name_ua="Лебедин", name_en="Lebedyn")
    zolochiv = _create_simle_name_entity(service=city_service, name_ua="Золочів", name_en="Zolochiv")
    kaniv = _create_simle_name_entity(service=city_service, name_ua="Канів", name_en="Kaniv")
    berehove = _create_simle_name_entity(service=city_service, name_ua="Берегове", name_en="Berehove")
    brody = _create_simle_name_entity(service=city_service, name_ua="Броди", name_en="Brody")
    hadiach = _create_simle_name_entity(service=city_service, name_ua="Гадяч", name_en="Hadiach")
    dokuchaievsk = _create_simle_name_entity(service=city_service, name_ua="Докучаєвськ", name_en="Dokuchaievsk")
    koziatyn = _create_simle_name_entity(service=city_service, name_ua="Козятин", name_en="Koziatyn")
    ladyzhyn = _create_simle_name_entity(service=city_service, name_ua="Ладижин", name_en="Ladyzhyn")
    nadvirna = _create_simle_name_entity(service=city_service, name_ua="Надвірна", name_en="Nadvirna")
    molodohvardiisk = _create_simle_name_entity(service=city_service, name_ua="Молодо­гвардійськ", name_en="Molodohvardiisk")
    vilnohirsk = _create_simle_name_entity(service=city_service, name_ua="Вільногірськ", name_en="Vilnohirsk")
    krolevets = _create_simle_name_entity(service=city_service, name_ua="Кролевець", name_en="Krolevets")
    selydove = _create_simle_name_entity(service=city_service, name_ua="Селидове", name_en="Selydove")
    znamianka = _create_simle_name_entity(service=city_service, name_ua="Знам'янка", name_en="Znamianka")
    volnovakha = _create_simle_name_entity(service=city_service, name_ua="Волноваха", name_en="Volnovakha")
    merefa = _create_simle_name_entity(service=city_service, name_ua="Мерефа", name_en="Merefa")
    armiansk = _create_simle_name_entity(service=city_service, name_ua="Армянськ", name_en="Armiansk")
    kremenets = _create_simle_name_entity(service=city_service, name_ua="Кременець", name_en="Kremenets")
    sokal = _create_simle_name_entity(service=city_service, name_ua="Сокаль", name_en="Sokal")
    dolyna = _create_simle_name_entity(service=city_service, name_ua="Долина", name_en="Dolyna")
    sukhodilsk = _create_simle_name_entity(service=city_service, name_ua="Суходільськ", name_en="Sukhodilsk")
    polonne = _create_simle_name_entity(service=city_service, name_ua="Полонне", name_en="Polonne")
    lyman = _create_simle_name_entity(service=city_service, name_ua="Лиман", name_en="Lyman")
    stebnyk = _create_simle_name_entity(service=city_service, name_ua="Стебник", name_en="Stebnyk")
    liubotyn = _create_simle_name_entity(service=city_service, name_ua="Люботин", name_en="Liubotyn")
    krasnohrad = _create_simle_name_entity(service=city_service, name_ua="Красноград", name_en="Krasnohrad")
    trostianets = _create_simle_name_entity(service=city_service, name_ua="Тростянець", name_en="Trostianets")
    popasna = _create_simle_name_entity(service=city_service, name_ua="Попасна", name_en="Popasna")
    yahotyn = _create_simle_name_entity(service=city_service, name_ua="Яготин", name_en="Yahotyn")
    henichesk = _create_simle_name_entity(service=city_service, name_ua="Генічеськ", name_en="Henichesk")
    kiliia = _create_simle_name_entity(service=city_service, name_ua="Кілія", name_en="Kiliia")
    kalynivka = _create_simle_name_entity(service=city_service, name_ua="Калинівка", name_en="Kalynivka")
    krasyliv = _create_simle_name_entity(service=city_service, name_ua="Красилів", name_en="Krasyliv")
    kurakhove = _create_simle_name_entity(service=city_service, name_ua="Курахове", name_en="Kurakhove")
    volochysk = _create_simle_name_entity(service=city_service, name_ua="Волочиськ", name_en="Volochysk")
    piatykhatky = _create_simle_name_entity(service=city_service, name_ua="П'ятихатки", name_en="Piatykhatky")
    kreminna = _create_simle_name_entity(service=city_service, name_ua="Кремінна", name_en="Kreminna")
    polohy = _create_simle_name_entity(service=city_service, name_ua="Пологи", name_en="Polohy")
    balta = _create_simle_name_entity(service=city_service, name_ua="Балта", name_en="Balta")
    amvrosiivka = _create_simle_name_entity(service=city_service, name_ua="Амвросіївка", name_en="Amvrosiivka")
    dniprorudne = _create_simle_name_entity(service=city_service, name_ua="Дніпрорудне", name_en="Dniprorudne")
    reni = _create_simle_name_entity(service=city_service, name_ua="Рені", name_en="Reni")
    vovchansk = _create_simle_name_entity(service=city_service, name_ua="Вовчанськ", name_en="Vovchansk")
    derhachi = _create_simle_name_entity(service=city_service, name_ua="Дергачі", name_en="Derhachi")
    bakhmach = _create_simle_name_entity(service=city_service, name_ua="Бахмач", name_en="Bakhmach")
    starobilsk = _create_simle_name_entity(service=city_service, name_ua="Старобільськ", name_en="Starobilsk")
    vatutine = _create_simle_name_entity(service=city_service, name_ua="Ватутіне", name_en="Vatutine")
    zvenyhorodka = _create_simle_name_entity(service=city_service, name_ua="Звенигородка", name_en="Zvenyhorodka")
    zuhres = _create_simle_name_entity(service=city_service, name_ua="Зугрес", name_en="Zuhres")
    skadovsk = _create_simle_name_entity(service=city_service, name_ua="Скадовськ", name_en="Skadovsk")
    svatove = _create_simle_name_entity(service=city_service, name_ua="Сватове", name_en="Svatove")
    shpola = _create_simle_name_entity(service=city_service, name_ua="Шпола", name_en="Shpola")
    novoukrainka = _create_simle_name_entity(service=city_service, name_ua="Новоукраїнка", name_en="Novoukrainka")
    korsun_shevchenkivskyi = _create_simle_name_entity(service=city_service, name_ua="Корсунь-Шевченківський", name_en="Korsun-Shevchenkivskyi")
    lutuhyne = _create_simle_name_entity(service=city_service, name_ua="Лутугине", name_en="Lutuhyne")
    bilohirsk = _create_simle_name_entity(service=city_service, name_ua="Білогірськ", name_en="Bilohirsk")
    dolynska = _create_simle_name_entity(service=city_service, name_ua="Долинська", name_en="Dolynska")
    iziaslav = _create_simle_name_entity(service=city_service, name_ua="Ізяслав", name_en="Iziaslav")
    bilopillia = _create_simle_name_entity(service=city_service, name_ua="Білопілля", name_en="Bilopillia")
    bohodukhiv = _create_simle_name_entity(service=city_service, name_ua="Богодухів", name_en="Bohodukhiv")
    skvyra = _create_simle_name_entity(service=city_service, name_ua="Сквира", name_en="Skvyra")
    karlivka = _create_simle_name_entity(service=city_service, name_ua="Карлівка", name_en="Karlivka")
    orikhiv = _create_simle_name_entity(service=city_service, name_ua="Оріхів", name_en="Orikhiv")
    bilozerske = _create_simle_name_entity(service=city_service, name_ua="Білозерське", name_en="Bilozerske")
    zolote = _create_simle_name_entity(service=city_service, name_ua="Золоте", name_en="Zolote")
    yunokomunarivsk = _create_simle_name_entity(service=city_service, name_ua="Бунге (Bunhe)", name_en="Yunokomunarivsk")
    pidhorodne = _create_simle_name_entity(service=city_service, name_ua="Підгородне", name_en="Pidhorodne")
    rozdilna = _create_simle_name_entity(service=city_service, name_ua="Роздільна", name_en="Rozdilna")
    horodok = _create_simle_name_entity(service=city_service, name_ua="Городок", name_en="Horodok")
    chervonopartyzansk = _create_simle_name_entity(service=city_service, name_ua="Вознесенівка (Voznesenivka)", name_en="Chervonopartyzansk")
    ilovaisk = _create_simle_name_entity(service=city_service, name_ua="Іловайськ", name_en="Ilovaisk")
    berezhany = _create_simle_name_entity(service=city_service, name_ua="Бережани", name_en="Berezhany")
    novohrodivka = _create_simle_name_entity(service=city_service, name_ua="Новогродівка", name_en="Novohrodivka")
    vuhledar = _create_simle_name_entity(service=city_service, name_ua="Вугледар", name_en="Vuhledar")
    berezan = _create_simle_name_entity(service=city_service, name_ua="Березань", name_en="Berezan")
    putyvl = _create_simle_name_entity(service=city_service, name_ua="Путивль", name_en="Putyvl")
    bolhrad = _create_simle_name_entity(service=city_service, name_ua="Болград", name_en="Bolhrad")
    bar = _create_simle_name_entity(service=city_service, name_ua="Бар", name_en="Bar")
    svaliava = _create_simle_name_entity(service=city_service, name_ua="Свалява", name_en="Svaliava")
    bohuslav = _create_simle_name_entity(service=city_service, name_ua="Богуслав", name_en="Bohuslav")
    huliaipole = _create_simle_name_entity(service=city_service, name_ua="Гуляйполе", name_en="Huliaipole")
    zmiiv = _create_simle_name_entity(service=city_service, name_ua="Зміїв", name_en="Zmiiv")
    ovruch = _create_simle_name_entity(service=city_service, name_ua="Овруч", name_en="Ovruch")
    verkhnodniprovsk = _create_simle_name_entity(service=city_service, name_ua="Верхньодніп­ровськ", name_en="Verkhnodniprovsk")
    ochakiv = _create_simle_name_entity(service=city_service, name_ua="Очаків", name_en="Ochakiv")
    krasnohorivka = _create_simle_name_entity(service=city_service, name_ua="Красногорівка", name_en="Krasnohorivka")
    kivertsi = _create_simle_name_entity(service=city_service, name_ua="Ківерці", name_en="Kivertsi")
    pyriatyn = _create_simle_name_entity(service=city_service, name_ua="Пирятин", name_en="Pyriatyn")
    mykolaivka = _create_simle_name_entity(service=city_service, name_ua="Миколаївка", name_en="Mykolaivka")
    chasiv_yar = _create_simle_name_entity(service=city_service, name_ua="Часів Яр", name_en="Chasiv Yar")
    vilniansk = _create_simle_name_entity(service=city_service, name_ua="Вільнянськ", name_en="Vilniansk")
    dunaivtsi = _create_simle_name_entity(service=city_service, name_ua="Дунаївці", name_en="Dunaivtsi")
    apostolove = _create_simle_name_entity(service=city_service, name_ua="Апостолове", name_en="Apostolove")
    talne = _create_simle_name_entity(service=city_service, name_ua="Тальне", name_en="Talne")
    artsyz = _create_simle_name_entity(service=city_service, name_ua="Арциз", name_en="Artsyz")
    novyi_buh = _create_simle_name_entity(service=city_service, name_ua="Новий Буг", name_en="Novyi Buh")
    tulchyn = _create_simle_name_entity(service=city_service, name_ua="Тульчин", name_en="Tulchyn")
    haivoron = _create_simle_name_entity(service=city_service, name_ua="Гайворон", name_en="Haivoron")
    horodok = _create_simle_name_entity(service=city_service, name_ua="Городок", name_en="Horodok")
    hola_prystan = _create_simle_name_entity(service=city_service, name_ua="Гола Пристань", name_en="Hola Prystan")
    nosivka = _create_simle_name_entity(service=city_service, name_ua="Носівка", name_en="Nosivka")
    zhashkiv = _create_simle_name_entity(service=city_service, name_ua="Жашків", name_en="Zhashkiv")
    horodyshche = _create_simle_name_entity(service=city_service, name_ua="Городище", name_en="Horodyshche")
    vasylivka = _create_simle_name_entity(service=city_service, name_ua="Василівка", name_en="Vasylivka")
    kamianka_dniprovska = _create_simle_name_entity(service=city_service, name_ua="Кам'янка-Дніпровська", name_en="Kamianka-Dniprovska")
    petrovske = _create_simle_name_entity(service=city_service, name_ua="Петровське", name_en="Petrovske")
    beryslav = _create_simle_name_entity(service=city_service, name_ua="Берислав", name_en="Beryslav")
    snihurivka = _create_simle_name_entity(service=city_service, name_ua="Снігурівка", name_en="Snihurivka")
    radomyshl = _create_simle_name_entity(service=city_service, name_ua="Радомишль", name_en="Radomyshl")
    burshtyn = _create_simle_name_entity(service=city_service, name_ua="Бурштин", name_en="Burshtyn")
    rakhiv = _create_simle_name_entity(service=city_service, name_ua="Рахів", name_en="Rakhiv")
    novhorod_siverskyi = _create_simle_name_entity(service=city_service, name_ua="Новгород-Сіверський", name_en="Novhorod-Siverskyi")
    kamianka = _create_simle_name_entity(service=city_service, name_ua="Кам'янка", name_en="Kamianka")
    tetiiv = _create_simle_name_entity(service=city_service, name_ua="Тетіїв", name_en="Tetiiv")
    ostroh = _create_simle_name_entity(service=city_service, name_ua="Острог", name_en="Ostroh")
    zelenodolsk = _create_simle_name_entity(service=city_service, name_ua="Зеленодольськ", name_en="Zelenodolsk")
    vakhrusheve = _create_simle_name_entity(service=city_service, name_ua="Боково-Хрустальне (Bokovo-Khrustalne)", name_en="Vakhrusheve")
    khorol = _create_simle_name_entity(service=city_service, name_ua="Хорол", name_en="Khorol")
    storozhynets = _create_simle_name_entity(service=city_service, name_ua="Сторожинець", name_en="Storozhynets")
    sudak = _create_simle_name_entity(service=city_service, name_ua="Судак", name_en="Sudak")
    siversk = _create_simle_name_entity(service=city_service, name_ua="Сіверськ", name_en="Siversk")
    koriukivka = _create_simle_name_entity(service=city_service, name_ua="Корюківка", name_en="Koriukivka")
    biliaivka = _create_simle_name_entity(service=city_service, name_ua="Біляївка", name_en="Biliaivka")
    hirnyk = _create_simle_name_entity(service=city_service, name_ua="Гірник", name_en="Hirnyk")
    ukrainka = _create_simle_name_entity(service=city_service, name_ua="Українка", name_en="Ukrainka")
    nova_odesa = _create_simle_name_entity(service=city_service, name_ua="Нова Одеса", name_en="Nova Odesa")
    horodnia = _create_simle_name_entity(service=city_service, name_ua="Городня", name_en="Horodnia")
    shchastia = _create_simle_name_entity(service=city_service, name_ua="Щастя", name_en="Shchastia")
    kaharlyk = _create_simle_name_entity(service=city_service, name_ua="Кагарлик", name_en="Kaharlyk")
    zhdanivka = _create_simle_name_entity(service=city_service, name_ua="Жданівка", name_en="Zhdanivka")
    berezne = _create_simle_name_entity(service=city_service, name_ua="Березне", name_en="Berezne")
    terebovlia = _create_simle_name_entity(service=city_service, name_ua="Теребовля", name_en="Terebovlia")
    vynnyky = _create_simle_name_entity(service=city_service, name_ua="Винники", name_en="Vynnyky")
    rozhyshche = _create_simle_name_entity(service=city_service, name_ua="Рожище", name_en="Rozhyshche")
    yavoriv = _create_simle_name_entity(service=city_service, name_ua="Яворів", name_en="Yavoriv")
    zhovkva = _create_simle_name_entity(service=city_service, name_ua="Жовква", name_en="Zhovkva")
    tarashcha = _create_simle_name_entity(service=city_service, name_ua="Тараща", name_en="Tarashcha")
    myronivka = _create_simle_name_entity(service=city_service, name_ua="Миронівка", name_en="Myronivka")
    bershad = _create_simle_name_entity(service=city_service, name_ua="Бершадь", name_en="Bershad")
    ukrainsk = _create_simle_name_entity(service=city_service, name_ua="Українськ", name_en="Ukrainsk")
    zbarazh = _create_simle_name_entity(service=city_service, name_ua="Збараж", name_en="Zbarazh")
    novomyrhorod = _create_simle_name_entity(service=city_service, name_ua="Новомиргород", name_en="Novomyrhorod")
    uzyn = _create_simle_name_entity(service=city_service, name_ua="Узин", name_en="Uzyn")
    svitlodarsk = _create_simle_name_entity(service=city_service, name_ua="Світлодарськ", name_en="Svitlodarsk")
    soledar = _create_simle_name_entity(service=city_service, name_ua="Соледар", name_en="Soledar")
    bashtanka = _create_simle_name_entity(service=city_service, name_ua="Баштанка", name_en="Bashtanka")
    mala_vyska = _create_simle_name_entity(service=city_service, name_ua="Мала Виска", name_en="Mala Vyska")
    irmino = _create_simle_name_entity(service=city_service, name_ua="Ірміно", name_en="Irmino")
    barvinkove = _create_simle_name_entity(service=city_service, name_ua="Барвінкове", name_en="Barvinkove")
    prymorsk = _create_simle_name_entity(service=city_service, name_ua="Приморськ", name_en="Prymorsk")
    mena = _create_simle_name_entity(service=city_service, name_ua="Мена", name_en="Mena")
    hlobyne = _create_simle_name_entity(service=city_service, name_ua="Глобине", name_en="Hlobyne")
    hnivan = _create_simle_name_entity(service=city_service, name_ua="Гнівань", name_en="Hnivan")
    komsomolske = _create_simle_name_entity(service=city_service, name_ua="Кальміуське (Kalmiuske)", name_en="Komsomolske")
    ichnia = _create_simle_name_entity(service=city_service, name_ua="Ічня", name_en="Ichnia")
    novoazovsk = _create_simle_name_entity(service=city_service, name_ua="Новоазовськ", name_en="Novoazovsk")
    baranivka = _create_simle_name_entity(service=city_service, name_ua="Баранівка", name_en="Baranivka")
    buchach = _create_simle_name_entity(service=city_service, name_ua="Бучач", name_en="Buchach")
    lokhvytsia = _create_simle_name_entity(service=city_service, name_ua="Лохвиця", name_en="Lokhvytsia")
    snovsk = _create_simle_name_entity(service=city_service, name_ua="Сновськ", name_en="Snovsk")
    bobrynets = _create_simle_name_entity(service=city_service, name_ua="Бобринець", name_en="Bobrynets")
    nemyriv = _create_simle_name_entity(service=city_service, name_ua="Немирів", name_en="Nemyriv")
    kobeliaky = _create_simle_name_entity(service=city_service, name_ua="Кобеляки", name_en="Kobeliaky")
    rodynske = _create_simle_name_entity(service=city_service, name_ua="Родинське", name_en="Rodynske")
    chyhyryn = _create_simle_name_entity(service=city_service, name_ua="Чигирин", name_en="Chyhyryn")
    bobrovytsia = _create_simle_name_entity(service=city_service, name_ua="Бобровиця", name_en="Bobrovytsia")
    sosnivka = _create_simle_name_entity(service=city_service, name_ua="Соснівка", name_en="Sosnivka")
    zhydachiv = _create_simle_name_entity(service=city_service, name_ua="Жидачів", name_en="Zhydachiv")
    yampil = _create_simle_name_entity(service=city_service, name_ua="Ямпіль", name_en="Yampil")
    mospyne = _create_simle_name_entity(service=city_service, name_ua="Моспине", name_en="Mospyne")
    borzna = _create_simle_name_entity(service=city_service, name_ua="Борзна", name_en="Borzna")
    shcholkine = _create_simle_name_entity(service=city_service, name_ua="Щолкіне", name_en="Shcholkine")
    buryn = _create_simle_name_entity(service=city_service, name_ua="Буринь", name_en="Buryn")
    kamianka_buzka = _create_simle_name_entity(service=city_service, name_ua="Кам'янка-Бузька", name_en="Kamianka-Buzka")
    hrebinka = _create_simle_name_entity(service=city_service, name_ua="Гребінка", name_en="Hrebinka")
    khrystynivka = _create_simle_name_entity(service=city_service, name_ua="Христинівка", name_en="Khrystynivka")
    hirske = _create_simle_name_entity(service=city_service, name_ua="Гірське", name_en="Hirske")
    tavriisk = _create_simle_name_entity(service=city_service, name_ua="Таврійськ", name_en="Tavriisk")
    borshchiv = _create_simle_name_entity(service=city_service, name_ua="Борщів", name_en="Borshchiv")
    zymohiria = _create_simle_name_entity(service=city_service, name_ua="Зимогір'я", name_en="Zymohiria")
    khotyn = _create_simle_name_entity(service=city_service, name_ua="Хотин", name_en="Khotyn")
    illintsi = _create_simle_name_entity(service=city_service, name_ua="Іллінці", name_en="Illintsi")
    pomichna = _create_simle_name_entity(service=city_service, name_ua="Помічна", name_en="Pomichna")
    olevsk = _create_simle_name_entity(service=city_service, name_ua="Олевськ", name_en="Olevsk")
    kamin_kashyrskyi = _create_simle_name_entity(service=city_service, name_ua="Камінь-Каширський", name_en="Kamin-Kashyrskyi")
    tatarbunary = _create_simle_name_entity(service=city_service, name_ua="Татарбунари", name_en="Tatarbunary")
    pohrebyshche = _create_simle_name_entity(service=city_service, name_ua="Погребище", name_en="Pohrebyshche")
    marinka = _create_simle_name_entity(service=city_service, name_ua="Мар'їнка", name_en="Marinka")
    bolekhiv = _create_simle_name_entity(service=city_service, name_ua="Болехів", name_en="Bolekhiv")
    inkerman = _create_simle_name_entity(service=city_service, name_ua="Інкерман", name_en="Inkerman")
    zinkiv = _create_simle_name_entity(service=city_service, name_ua="Зіньків", name_en="Zinkiv")
    khodoriv = _create_simle_name_entity(service=city_service, name_ua="Ходорів", name_en="Khodoriv")
    sniatyn = _create_simle_name_entity(service=city_service, name_ua="Снятин", name_en="Sniatyn")
    derazhnia = _create_simle_name_entity(service=city_service, name_ua="Деражня", name_en="Derazhnia")
    liuboml = _create_simle_name_entity(service=city_service, name_ua="Любомль", name_en="Liuboml")
    valky = _create_simle_name_entity(service=city_service, name_ua="Валки", name_en="Valky")
    novodnistrovsk = _create_simle_name_entity(service=city_service, name_ua="Новодністровськ", name_en="Novodnistrovsk")
    radyvyliv = _create_simle_name_entity(service=city_service, name_ua="Радивилів", name_en="Radyvyliv")
    vuhlehirsk = _create_simle_name_entity(service=city_service, name_ua="Вуглегірськ", name_en="Vuhlehirsk")
    sokyriany = _create_simle_name_entity(service=city_service, name_ua="Сокиряни", name_en="Sokyriany")
    verkhivtseve = _create_simle_name_entity(service=city_service, name_ua="Верхівцеве", name_en="Verkhivtseve")
    zalishchyky = _create_simle_name_entity(service=city_service, name_ua="Заліщики", name_en="Zalishchyky")
    staryi_krym = _create_simle_name_entity(service=city_service, name_ua="Старий Крим", name_en="Staryi Krym")
    bilytske = _create_simle_name_entity(service=city_service, name_ua="Білицьке", name_en="Bilytske")
    pereshchepyne = _create_simle_name_entity(service=city_service, name_ua="Перещепине", name_en="Pereshchepyne")
    andrushivka = _create_simle_name_entity(service=city_service, name_ua="Андрушівка", name_en="Andrushivka")
    pustomyty = _create_simle_name_entity(service=city_service, name_ua="Пустомити", name_en="Pustomyty")
    horodenka = _create_simle_name_entity(service=city_service, name_ua="Городенка", name_en="Horodenka")
    tysmenytsia = _create_simle_name_entity(service=city_service, name_ua="Тисмениця", name_en="Tysmenytsia")
    tiachiv = _create_simle_name_entity(service=city_service, name_ua="Тячів", name_en="Tiachiv")
    semenivka = _create_simle_name_entity(service=city_service, name_ua="Семенівка", name_en="Semenivka")
    dubrovytsia = _create_simle_name_entity(service=city_service, name_ua="Дубровиця", name_en="Dubrovytsia")
    kodyma = _create_simle_name_entity(service=city_service, name_ua="Кодима", name_en="Kodyma")
    irshava = _create_simle_name_entity(service=city_service, name_ua="Іршава", name_en="Irshava")
    berezivka = _create_simle_name_entity(service=city_service, name_ua="Березівка", name_en="Berezivka")
    ananiv = _create_simle_name_entity(service=city_service, name_ua="Ананьїв", name_en="Ananiv")
    monastyryshche = _create_simle_name_entity(service=city_service, name_ua="Монастирище", name_en="Monastyryshche")
    reshetylivka = _create_simle_name_entity(service=city_service, name_ua="Решетилівка", name_en="Reshetylivka")
    lypovets = _create_simle_name_entity(service=city_service, name_ua="Липовець", name_en="Lypovets")
    vylkove = _create_simle_name_entity(service=city_service, name_ua="Вилкове", name_en="Vylkove")
    radekhiv = _create_simle_name_entity(service=city_service, name_ua="Радехів", name_en="Radekhiv")
    mostyska = _create_simle_name_entity(service=city_service, name_ua="Мостиська", name_en="Mostyska")
    artemivsk = _create_simle_name_entity(service=city_service, name_ua="Кипуче (Kypuche)", name_en="Artemivsk")
    novodruzhesk = _create_simle_name_entity(service=city_service, name_ua="Новодружеськ", name_en="Novodruzhesk")
    zavodske = _create_simle_name_entity(service=city_service, name_ua="Заводське", name_en="Zavodske")
    alupka = _create_simle_name_entity(service=city_service, name_ua="Алупка", name_en="Alupka")
    horokhiv = _create_simle_name_entity(service=city_service, name_ua="Горохів", name_en="Horokhiv")
    pryvillia = _create_simle_name_entity(service=city_service, name_ua="Привілля", name_en="Pryvillia")
    chop = _create_simle_name_entity(service=city_service, name_ua="Чоп", name_en="Chop")
    zastavna = _create_simle_name_entity(service=city_service, name_ua="Заставна", name_en="Zastavna")
    zorynsk = _create_simle_name_entity(service=city_service, name_ua="Зоринськ", name_en="Zorynsk")
    tlumach = _create_simle_name_entity(service=city_service, name_ua="Тлумач", name_en="Tlumach")
    teplodar = _create_simle_name_entity(service=city_service, name_ua="Теплодар", name_en="Teplodar")
    lanivtsi = _create_simle_name_entity(service=city_service, name_ua="Ланівці", name_en="Lanivtsi")
    busk = _create_simle_name_entity(service=city_service, name_ua="Буськ", name_en="Busk")
    korets = _create_simle_name_entity(service=city_service, name_ua="Корець", name_en="Korets")
    rohatyn = _create_simle_name_entity(service=city_service, name_ua="Рогатин", name_en="Rohatyn")
    pivdenne = _create_simle_name_entity(service=city_service, name_ua="Південне", name_en="Pivdenne")
    dubliany = _create_simle_name_entity(service=city_service, name_ua="Дубляни", name_en="Dubliany")
    rzhyshchiv = _create_simle_name_entity(service=city_service, name_ua="Ржищів", name_en="Rzhyshchiv")
    novoselytsia = _create_simle_name_entity(service=city_service, name_ua="Новоселиця", name_en="Novoselytsia")
    vorozhba = _create_simle_name_entity(service=city_service, name_ua="Ворожба", name_en="Vorozhba")
    kosiv = _create_simle_name_entity(service=city_service, name_ua="Косів", name_en="Kosiv")
    pochaiv = _create_simle_name_entity(service=city_service, name_ua="Почаїв", name_en="Pochaiv")
    rava_ruska = _create_simle_name_entity(service=city_service, name_ua="Рава-руська", name_en="Rava-Ruska")
    molochansk = _create_simle_name_entity(service=city_service, name_ua="Молочанськ", name_en="Molochansk")
    yaremche = _create_simle_name_entity(service=city_service, name_ua="Яремче", name_en="Yaremche")
    turka = _create_simle_name_entity(service=city_service, name_ua="Турка", name_en="Turka")
    kitsman = _create_simle_name_entity(service=city_service, name_ua="Кіцмань", name_en="Kitsman")
    peremyshliany = _create_simle_name_entity(service=city_service, name_ua="Перемишляни", name_en="Peremyshliany")
    blahovishchenske = _create_simle_name_entity(service=city_service, name_ua="Благовіщенське", name_en="Blahovishchenske")
    seredyna_buda = _create_simle_name_entity(service=city_service, name_ua="Середина-Буда", name_en="Seredyna-Buda")
    zboriv = _create_simle_name_entity(service=city_service, name_ua="Зборів", name_en="Zboriv")
    khorostkiv = _create_simle_name_entity(service=city_service, name_ua="Хоростків", name_en="Khorostkiv")
    oster = _create_simle_name_entity(service=city_service, name_ua="Остер", name_en="Oster")
    sharhorod = _create_simle_name_entity(service=city_service, name_ua="Шаргород", name_en="Sharhorod")
    perechyn = _create_simle_name_entity(service=city_service, name_ua="Перечин", name_en="Perechyn")
    oleksandrivsk = _create_simle_name_entity(service=city_service, name_ua="Олександрівськ", name_en="Oleksandrivsk")
    kopychyntsi = _create_simle_name_entity(service=city_service, name_ua="Копичинці", name_en="Kopychyntsi")
    skole = _create_simle_name_entity(service=city_service, name_ua="Сколе", name_en="Skole")
    zalizne = _create_simle_name_entity(service=city_service, name_ua="Залізне", name_en="Zalizne")
    sudova_vyshnia = _create_simle_name_entity(service=city_service, name_ua="Судова Вишня", name_en="Sudova Vyshnia")
    halych = _create_simle_name_entity(service=city_service, name_ua="Галич", name_en="Halych")
    morshyn = _create_simle_name_entity(service=city_service, name_ua="Моршин", name_en="Morshyn")
    monastyryska = _create_simle_name_entity(service=city_service, name_ua="Монастириська", name_en="Monastyryska")
    miusynsk = _create_simle_name_entity(service=city_service, name_ua="Міусинськ", name_en="Miusynsk")
    vashkivtsi = _create_simle_name_entity(service=city_service, name_ua="Вашківці", name_en="Vashkivtsi")
    velyki_mosty = _create_simle_name_entity(service=city_service, name_ua="Великі Мости", name_en="Velyki Mosty")
    druzhba = _create_simle_name_entity(service=city_service, name_ua="Дружба", name_en="Druzhba")
    staryi_sambir = _create_simle_name_entity(service=city_service, name_ua="Старий Самбір", name_en="Staryi Sambir")
    broshniv_osada = _create_simle_name_entity(service=city_service, name_ua="Брошнів-Осада", name_en="Broshniv-Osada")
    chudniv = _create_simle_name_entity(service=city_service, name_ua="Чуднів", name_en="Chudniv")
    shumsk = _create_simle_name_entity(service=city_service, name_ua="Шумськ", name_en="Shumsk")
    sviatohirsk = _create_simle_name_entity(service=city_service, name_ua="Святогірськ", name_en="Sviatohirsk")
    almazna = _create_simle_name_entity(service=city_service, name_ua="Алмазна", name_en="Almazna")
    vyzhnytsia = _create_simle_name_entity(service=city_service, name_ua="Вижниця", name_en="Vyzhnytsia")
    dobromyl = _create_simle_name_entity(service=city_service, name_ua="Добромиль", name_en="Dobromyl")
    rudky = _create_simle_name_entity(service=city_service, name_ua="Рудки", name_en="Rudky")
    khyriv = _create_simle_name_entity(service=city_service, name_ua="Хирів", name_en="Khyriv")
    skalat = _create_simle_name_entity(service=city_service, name_ua="Скалат", name_en="Skalat")
    komarno = _create_simle_name_entity(service=city_service, name_ua="Комарно", name_en="Komarno")
    bibrka = _create_simle_name_entity(service=city_service, name_ua="Бібрка", name_en="Bibrka")
    novyi_kalyniv = _create_simle_name_entity(service=city_service, name_ua="Новий Калинів", name_en="Novyi Kalyniv")
    hlyniany = _create_simle_name_entity(service=city_service, name_ua="Глиняни", name_en="Hlyniany")
    pidhaitsi = _create_simle_name_entity(service=city_service, name_ua="Підгайці", name_en="Pidhaitsi")
    baturyn = _create_simle_name_entity(service=city_service, name_ua="Батурин", name_en="Baturyn")
    belz = _create_simle_name_entity(service=city_service, name_ua="Белз", name_en="Belz")
    ustyluh = _create_simle_name_entity(service=city_service, name_ua="Устилуг", name_en="Ustyluh")
    hertsa = _create_simle_name_entity(service=city_service, name_ua="Герца", name_en="Hertsa")
    berestechko = _create_simle_name_entity(service=city_service, name_ua="Берестечко", name_en="Berestechko")
    chernobyl = _create_simle_name_entity(service=city_service, name_ua="Чорнобиль", name_en="Chernobyl")
    uhniv = _create_simle_name_entity(service=city_service, name_ua="Угнів", name_en="Uhniv")
    pripyat = _create_simle_name_entity(service=city_service, name_ua="Прип'ять", name_en="Pripyat")
